In [15]:
import numpy as np
import pandas as pd

In [27]:
reddit_df = pd.read_json('../data/rough_redditapi_data.json')

reddit_df

,approved_at_utc,subreddit,selftext,author_fullname,saved,mod_reason_title,gilded,clicked,title,link_flair_richtext,...,url,subreddit_subscribers,created_utc,num_crossposts,media,is_video,post_hint,url_overridden_by_dest,preview,media_metadata
0,NaN,developersIndia,The Community Team on developersIndia is looki...,t2_2gaojwjr,False,NaN,0,False,📢 Call For Volunteers: Help us build r/develop...,"[{'e': 'text', 't': 'Announcement'}, {'a': ':s...",...,https://www.reddit.com/r/developersIndia/comme...,1332117,1723203019,0,None,False,NaN,NaN,NaN,NaN
1,NaN,developersIndia,\nIt's time for our monthly showcase thread wh...,t2_4htru1we8,False,NaN,0,False,Showcase Sunday Megathread - May 2025,"[{'e': 'text', 't': 'Showcase Sunday '}, {'a':...",...,https://www.reddit.com/r/developersIndia/comme...,1332117,1746935576,0,None,False,NaN,NaN,NaN,NaN
2,NaN,developersIndia,Recently I applied for Remote Flutter internsh...,t2_fiqruud76,False,NaN,0,False,Free Work Culture In India | Why is it so Diff...,"[{'e': 'text', 't': 'Career'}]",...,https://www.reddit.com/r/developersIndia/comme...,1332117,1747738258,0,None,False,NaN,NaN,NaN,NaN
3,NaN,developersIndia,"Hi All, \nI work as a dev in one of the WITCH ...",t2_1aymiwjrxd,False,NaN,0,False,Salary Negotiation! Why some HRs take candidat...,"[{'e': 'text', 't': 'General'}]",...,https://www.reddit.com/r/developersIndia/comme...,1332117,1747713146,0,None,False,NaN,NaN,NaN,NaN
4,NaN,developersIndia,Anyone here work big tech companies without gi...,t2_18kwhws096,False,NaN,0,False,Anyone here work big tech companies without gi...,"[{'e': 'text', 't': 'General'}]",...,https://www.reddit.com/r/developersIndia/comme...,1332117,1747728843,0,None,False,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,NaN,developersIndia,"Hey everyone,\n\nDo anyone has idea about how ...",t2_14zc94enuy,False,NaN,0,False,"How to build cli like shadcn which can update,...","[{'e': 'text', 't': 'Help'}]",...,https://www.reddit.com/r/developersIndia/comme...,1332117,1747675231,0,None,False,NaN,NaN,NaN,NaN
98,NaN,developersIndia,YOE: 3.8 years\n\n💼 Microsoft Offer: L61\n\nBa...,t2_h12pr6yi,False,NaN,0,False,Offer comparison b/w apple and microsoft for 3...,"[{'e': 'text', 't': 'Career'}]",...,https://www.reddit.com/r/developersIndia/comme...,1332117,1747558556,1,None,False,NaN,NaN,NaN,NaN
99,NaN,developersIndia,"So i’ll keep it simple, im a BTech ECE graduat...",t2_1nb1x5696r,False,NaN,0,False,"Trying to learn programming , any help is much...","[{'e': 'text', 't': 'Career'}]",...,https://www.reddit.com/r/developersIndia/comme...,1332117,1747657846,0,None,False,NaN,NaN,NaN,NaN
100,NaN,developersIndia,Hello everyone. I don't know whether it is the...,t2_paohdgeum,False,NaN,0,False,I have created my first app and deployed it on...,"[{'e': 'text', 't': 'I Made This '}, {'a': ':s...",...,https://v.redd.it/7noy4yab6k1f1,1332117,1747582097,0,"{'reddit_video': {'bitrate_kbps': 800, 'fallba...",True,hosted:video,https://v.redd.it/7noy4yab6k1f1,{'images': [{'source': {'url': 'https://extern...,NaN
101,NaN,developersIndia,I'd started my career as an embedded automotiv...,t2_1ajajnkj0t,False,NaN,0,False,"Please help me in restarting back my career, n...","[{'e': 'text', 't': 'Career'}]",...,https://www.reddit.com/r/developersIndia/comme...,1332117,1747643727,0,None,False,NaN,NaN,NaN,NaN

In [28]:
cleaned_df = pd.read_json('../data/cleaned_reddit_data.json')

In [29]:
cleaned_df

,id,subreddit,title,selftext,ups,downs,upvote_ratio,score,edited,suggested_sort
0,1enxavp,developersIndia,📢 Call For Volunteers: Help us build r/develop...,The Community Team on developersIndia is looki...,9,0,0.91,9,0,confidence
1,1kjs21b,developersIndia,Showcase Sunday Megathread - May 2025,\nIt's time for our monthly showcase thread wh...,23,0,1.00,23,0,confidence
2,1kr1v1b,developersIndia,Free Work Culture In India | Why is it so Diff...,Recently I applied for Remote Flutter internsh...,111,0,0.98,111,0,confidence
3,1kqvmi1,developersIndia,Salary Negotiation! Why some HRs take candidat...,"Hi All, \nI work as a dev in one of the WITCH ...",261,0,0.97,261,0,confidence
4,1kqzl1g,developersIndia,Anyone here work big tech companies without gi...,Anyone here work big tech companies without gi...,107,0,0.92,107,0,confidence
...,...,...,...,...,...,...,...,...,...,...
97,1kqhf0j,developersIndia,"How to build cli like shadcn which can update,...","Hey everyone,\n\nDo anyone has idea about how ...",2,0,1.00,2,0,confidence
98,1kpfkbn,developersIndia,Offer comparison b/w apple and microsoft for 3...,YOE: 3.8 years\n\n💼 Microsoft Offer: L61\n\nBa...,680,0,0.94,680,1747560990,confidence
99,1kqah40,developersIndia,"Trying to learn programming , any help is much...","So i’ll keep it simple, im a BTech ECE graduat...",3,0,0.72,3,1747658952,confidence
100,1kpmls9,developersIndia,I have created my first app and deployed it on...,Hello everyone. I don't know whether it is the...,194,0,0.99,194,0,confidence
101,1kq6oaa,developersIndia,"Please help me in restarting back my career, n...",I'd started my career as an embedded automotiv...,8,0,0.90,8,1747731857,confidence